/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.AntrianPasien;
import model.Pasien;
import model.Dokter;
import model.Klinik;
/**
 *
 * @author admin
 */
public class TampilanDaftarPasien extends javax.swing.JPanel {

    /**
     * Creates new form TampilanDaftarPasien
     */
    public TampilanDaftarPasien(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NoRMText = new javax.swing.JTextField();
        DaftarPasienjLabel = new javax.swing.JLabel();
        NamaJLabel = new javax.swing.JLabel();
        SimpanButton = new javax.swing.JButton();
        namaText = new javax.swing.JTextField();
        AlamatText = new javax.swing.JTextField();
        NoRMJLabel = new javax.swing.JLabel();
        AlamatJLabel = new javax.swing.JLabel();

        NoRMText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoRMText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRMTextActionPerformed(evt);
            }
        });

        DaftarPasienjLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DaftarPasienjLabel.setText("Daftar Pasien");

        NamaJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaJLabel.setText("Nama");

        SimpanButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SimpanButton.setText("Save");

        namaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        AlamatText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AlamatText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatTextActionPerformed(evt);
            }
        });

        NoRMJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoRMJLabel.setText("No RM");

        AlamatJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AlamatJLabel.setText("Alamat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DaftarPasienjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoRMJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlamatJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoRMText, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlamatText, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(SimpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DaftarPasienjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoRMText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoRMJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlamatText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(SimpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public AntrianPasien antri = new AntrianPasien();
    
    private void NoRMTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRMTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRMTextActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void AlamatTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatJLabel;
    private javax.swing.JTextField AlamatText;
    private javax.swing.JLabel DaftarPasienjLabel;
    private javax.swing.JLabel NamaJLabel;
    private javax.swing.JLabel NoRMJLabel;
    private javax.swing.JTextField NoRMText;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JTextField namaText;
    // End of variables declaration//GEN-END:variables
}
